
name: Build containers

on: 
  push:
    branches:
    - main
    - master

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: amd64 (Intel/AMD)
      env:
        ARCH: amd64
      run: |
        make wrap-$(ARCH)
        make build-$(ARCH)
    - name: Push amd64
      run: | 
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        make push-$(ARCH)
        
  arm32v7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: arm32v7 (Pi 2 and 3)
      env:
        ARCH: arm32v7
      run: |
        make wrap-$(ARCH)
        make build-$(ARCH)
    - name: Push arm32v7
      run: | 
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        make push-$(ARCH)

  arm64v8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: arm64v8 (Pi 3+ and other aarch64)
      env:
        ARCH: arm64v8
      run: |
        make wrap-$(ARCH)
        make build-$(ARCH)
    - name: Push arm64v8
      run: | 
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        make push-$(ARCH)

  manifest:
    runs-on: ubuntu-latest
    needs: 
    - amd64
    - arm32v7
    - arm64v8
    steps: 
    - uses: actions/checkout@v1
    - name: multi-arch manifest
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        make manifest
